### ISSUE TITLE
CI - Run tests on windows and ubuntu

### ISSUE THREAD

**Issue by regislon** [EPFL-ENAC/gpm_api#1]

**Comment by regislon** [comment]
@ghiggi - Running tests on Windows may take longer since installation can be tricky. Therefore, it should be discussed at the end of Sprint 1.

**Comment by ghiggi** [comment]
I guess the simplest solution is to install the requirements with mamba/micromamba and not via pip (using an `environment.yaml` instead of `requirements.txt` file).
This is what is done by other geospatial software to avoid installation of `libgeos` or `libgdal-dev`.

We could just imitate what is done by: 
- xvec: [https://github.com/martinfleis/xvec/tree/main/ci](https://github.com/martinfleis/xvec/tree/main/ci) and [https://github.com/martinfleis/xvec/blob/main/.github/workflows/tests.yaml#L22](https://github.com/martinfleis/xvec/blob/main/.github/workflows/tests.yaml#L22)
- geopandas: [https://github.com/geopandas/geopandas/blob/main/.github/workflows/tests.yaml](https://github.com/geopandas/geopandas/blob/main/.github/workflows/tests.yaml) and [https://github.com/geopandas/geopandas/tree/main/ci/envs](https://github.com/geopandas/geopandas/tree/main/ci/envs)

```
      - name: setup micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: ${{ matrix.environment-file }}
          micromamba-version: "latest"
          channel-priority: "flexible"
```
